# CONFIG_SOC_POSIX=y
# CONFIG_BOARD_NATIVE_POSIX_32BIT=y
# CONFIG_UART_NATIVE_POSIX=y
# CONFIG_NATIVE_UART_0_ON_OWN_PTY=y
# CONFIG_NATIVE_UART_0_ON_STDINOUT=n
# CONFIG_UART_NATIVE_POSIX_PORT_1_ENABLE=n

CONFIG_CAN_NATIVE_POSIX=y
CONFIG_ETH_NATIVE_POSIX=n
CONFIG_CAN_NATIVE_POSIX_INTERFACE_1=y

CONFIG_NETWORKING=y
# CONFIG_CAN_NET=y
CONFIG_NET_L2_CANBUS=y
