CONFIG_BOARD_NATIVE_POSIX_32BIT=y
CONFIG_SOC_POSIX=y
CONFIG_UART_NATIVE_POSIX=y
CONFIG_NATIVE_UART_0_ON_OWN_PTY=y
CONFIG_NATIVE_UART_0_ON_STDINOUT=n
CONFIG_UART_NATIVE_POSIX_PORT_1_ENABLE=n

CONFIG_CAN=y
# CONFIG_CAN_INIT_PRIORITY=80
# CONFIG_CAN_MAX_FILTER=5
CONFIG_CAN_NATIVE_POSIX=y
CONFIG_NET_SOCKETS_CAN=y
CONFIG_NETWORKING=y

# CONFIG_SHELL=y
# CONFIG_CAN_SHELL=y
# CONFIG_DEVICE_SHELL=y
